users = [{"id": 1,
          "firstname": "Mandarin",
          "name": "Orange",
          "username": "s77518",
          "primary_email": 'bird@kakadu.com',
          "all_emails": ['bird@kakadu.com', 'kakadu@kamel.de'],
          "admin": True,
          "portal_groups": ['1', '2'],
          "k8s_account": 'default',
          "k8s_namespace": 'default',
          "k8s_token": 'default',
          "k8s_apiserver": 'default',
          "k8s_clustername": 'default'
          },
         {"id": 2,
          "firstname": "Tannenbaum",
          "name": "Ananas",
          "username": "Peter",
          "primary_email": 'bird@kakadu.com',
          "all_emails": ['bird@kakadu.com', 'kakadu@kamel.de'],
          "admin": True,
          "portal_groups": ['1', '2'],
          "k8s_account": 'default',
          "k8s_namespace": 'default',
          "k8s_token": 'default',
          "k8s_apiserver": 'default',
          "k8s_clustername": 'default'
          },
         {"id": 3,
          "firstname": "Mandarin",
          "name": "Mandarine",
          "username": "Kathi",
          "primary_email": 'bird@kakadu.com',
          "all_emails": ['bird@kakadu.com', 'kakadu@kamel.de'],
          "admin": True,
          "portal_groups": ['1', '2'],
          "k8s_account": 'default',
          "k8s_namespace": 'default',
          "k8s_token": 'default',
          "k8s_apiserver": 'default',
          "k8s_clustername": 'default'
          },
         ]

webapps = [{"name": "kakatoo",
            "link_show": "false",
            "link_name": "kuchen",
            "link_url": "https://mango.com",
            "oidc_client": "Kikeriki",
            "can_subauth": "true",
            },
           {"name": "Mango",
            "link_show": "false",
            "link_name": "kuchen",
            "link_url": "https://mango.com",
            "oidc_client": "Kikeriki",
            "can_subauth": "true",
            },
           {"name": "Hase",
            "link_show": "false",
            "link_name": "kuchen",
            "link_url": "https://mango.com",
            "oidc_client": "Kikeriki",
            "can_subauth": "true",
            },
           {"name": "Kolibri",
            "link_show": "false",
            "link_name": "kuchen",
            "link_url": "https://mango.com",
            "oidc_client": "Kikeriki",
            "can_subauth": "true",
            }
           ]

metrics = [{"Kubernetes": "v1.15.4"},
           {"API Server": "https://10.96.0.1:443"},
           {"Cluster Nodes": 24},
           {"CPU Cores": 1536},
           {"Main Memory": "12543.876796Gi"},
           {"Deployed Pods": 723},
           {"Allocated Volumes": 227},
           {"Portal Users": 120},
           {"KubePortal": "v.0.3.16"},
           ]
