apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeportal-api
  namespace: kubeportal-integration
  labels:
    app.kubernetes.io/name: kubeportal-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
